### PR TITLE
Use Tox-Travis for environment selection

### PR DESCRIPTION
**Pull request by astralblue**
Tox-Travis supports mapping each Travis factor (a value of os, language,
python, environment variables, etc.) onto zero or more Tox environment
name factors, so as to fully take advantage of generative listing of
environments in Tox 1.8+.  It eases testing with a matrix of dependency
version combinations.

Examples are in https://tox-travis.readthedocs.io/en/stable/toxenv.html

### CODE REVIEW

**Comment by eliasdorneles** [comment]
So, I suppose the broken build illustrates the advantage of the existing setup: it's compatible with Appveyor (and other non-Travis build systems). =)

**Comment by astralblue** [comment]
Not sure if that failure is directly caused by this change, because the build history shows that [another adjacent build](https://ci.appveyor.com/project/audreyr/cookiecutter-pypackage/build/1.0.328) triggered by pyup.io failed for the similar reason (OpenSSL compilation failure).  Not sure why that is happening though….

**Comment by astralblue** [comment]
Voila! (2)

**Comment by eliasdorneles** [comment]
Oh, I had misunderstood this PR before, this is actually pretty cool!
It enables one to set up a build matrix combining other env variables with the different python versions. :+1: 
Thanks!

**Pull request merged**
