### PR TITLE
Remove changelog directive. #80

### PR DESCRIPTION
**Pull request by bionikspoon**

### CODE REVIEW

**Comment by audreyr** [comment]
This is needed in order to display properly on PyPI. (Correct me if you have a better PyPI workaround, though.)

**Comment by audreyr** [comment]
Actually, @pydanny says it might not be needed anymore? Can you please verify?

**Comment by pydanny** [comment]
It was hackery on my part from a while back, and hasn't been needed in a while.

**Comment by audreyr** [comment]
Thanks @bionikspoon and @pydanny :thumbsup:

**Pull request merged**
