### PR TITLE
requirements_dev: Bump some versions.

### PR DESCRIPTION
**Pull request by JulienPalard**

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Hmm, dropping Python 2 support, are these changes intended for this PR?

**Comment by pydanny** [comment]
@JulienPalard, please remove the travis changes from this PR.

**Comment by JulienPalard** [comment]
Dropping Python2 support in 2017 *for new projects* (the usage of cookiecutter) looks the right move but let's not enter this subject, I'm openning another PR with only the bumps.

**Comment by JulienPalard** [comment]
→ https://github.com/audreyr/cookiecutter-pypackage/pull/313

**Pull request closed without merging**
