### PR TITLE
Change year to 2015 in cookiecutter.json

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by dogweather** [comment]
I saw this as well; you beat me to it.

How about it defaults to current year and date?

**Comment by dogweather** [comment]
I don't know how this piece of the template works, whether that'd be possible, though.

**Comment by westurner** [comment]
That would make sense.

**Comment by pydanny** [comment]
At some point I'll make this dynamic. Cookiecutter 0.9.1 allows for some fun tricks in the cookiecutter.json file. :smile:

**Pull request merged**
