### PR TITLE
Removing pytest, cookiecutter and PyYAML from requirements

### PR DESCRIPTION
**Pull request by rbanffy**
Removing pytest and cookiecutter (requirement of pytest-cookies), PyYAML (required by watchdog). Used pip-chill to trim down the list.

### CODE REVIEW

**Comment by pydanny** [comment]
Hi @rbanffy, care to resolve the merge conflicts?

**Comment by rbanffy** [comment]
Sure. Sorry not to have done this before - hectic week.

**Comment by pydanny** [comment]
@rbanffy, thank you so much for this pull request. However, in resolving some other stuff I closed the issue in 04d061efaadbf5f223aac50089ce980393a019e3. 

Nevertheless, I appreciated this PR and followed it closely in resolving some other things.

**Comment by rbanffy** [comment]
No problem. Whatever makes cookiecutter better, I'm in. :-)

**Pull request closed without merging**
