### PR TITLE
Add msys to PATH in appveyor, in order to run make (fixes #208)

### LINKED ISSUE #208: Get Appveyor build to pass on Windows
1. Study https://ci.appveyor.com/project/audreyr/cookiecutter-pypackage/branch/master and note that one of the tests is failing.
2. Get the test to pass:
   - Maybe you need to install make on the Appveyor worker by modifying `appveyor.yml`?
   - Maybe there is something else going on?

### PR DESCRIPTION
**Pull request by eliasdorneles**
This is an attempt to fix the AppVeyor build, as per answer here:
https://twitter.com/appveyor/status/502543860040335360

This of course doesn't eliminate the problem of relying on Make, perhaps one more reason for #172 .

Let's see if the build turn green.

### CODE REVIEW

**Comment by eliasdorneles** [comment]
Hm, tests are now passing but building the wheel fails:

```
%PYTHON%/python setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
 
error: invalid command 'bdist_wheel'
Command exited with code 1
```

Odd, since wheel is installed earlier:

```
%PYTHON%/Scripts/pip install wheel
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Installing collected packages: wheel
Successfully installed wheel-0.29.0
```

**Comment by eliasdorneles** [comment]
Something is off with the AppVeyor builds, the last one only got queued and never started.

@audreyr do you see anything in the admin interface?

**Comment by audreyr** [comment]
I combed through every option, found nothing. Appveyor also validated the YAML:

screen shot 2016-06-12 at 6 36 10 pm

We have a similar problem in Cookiecutter. I think Appveyor is just kind of flaky. If you or anyone knows of an alternative, we can try it.

**Comment by eliasdorneles** [comment]
Fixed by #225 -- thanks @JEStaubach !

**Pull request closed without merging**
