### PR TITLE
Define package version in version.py and then import that into setup.py

### PR DESCRIPTION
**Pull request by mw44118**
Hi -- This is a tiny tweak to make it easy to check the version of a package after it has been installed.

### CODE REVIEW

**Comment by mw44118** [comment]
There was a bug in the previous version.

**Comment by dogweather** [comment]
:+1:

**Comment by eliasdorneles** [comment]
Hm, this feels too tricky to me.

I'd rather have a `.bumpversion.cfg` generated by default and recommend users to use [bumpversion](https://pypi.python.org/pypi/bumpversion) for their releasing workflow.

**Comment by mw44118** [comment]
Didn't know about bumpversion.  That's interesting!

**Comment by glasslion** [comment]
[Python Packaging User Guide - Single-sourcing the Project Version](https://packaging.python.org/en/latest/single_source_version/) lists a few  techniques to store the version  without duplicating the value.

Each tech has its pros & cons. We can leave a link in the setup.py and let users choose.

**Comment by audreyr** [comment]
I'm playing around with bumpversion now. Thinking of closing this in favor of a generated `.bumpversion.cfg` to keep things simple.

**Pull request closed without merging**
